version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: innogram_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: innogram_db
    ports:
      - '5432:5432'

  mongo:
    image: mongo:6.0
    container_name: innogram_mongo
    ports:
      - '27017:27017'

  minio:
    image: minio/minio
    container_name: innogram_minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data --console-address ":9001"
  
  redis:
    image: redis:7-alpine
    container_name: innogram_redis
    ports:
      - '6379:6379'